import { useEffect, useMemo, useState } from 'react'
import { useMutation, useQuery } from '@tanstack/react-query'
import { useNavigate, useParams } from 'react-router-dom'
import type { ECTDNode, ConsistencyCheckResult } from '@platform/types'
import { regulatoryWritingApi } from '../../modules/regulatory-writing/api/regulatoryWriting'
import { useECTDStore } from '../../modules/regulatory-writing/store'
import { ECTDStatusDot, CTDReadOnlyBanner, ConsistencyContradictionCard } from '../../components/ui'

// Nodes flagged by the demo consistency check
const FLAGGED_NODE_IDS = new Set<string>(['nd-014', 'nd-018', 'nd-025'])

function formatDate(iso: string | null | undefined): string {
  if (!iso) return '—'
  const d = new Date(iso)
  if (Number.isNaN(d.getTime())) return '—'
  const months = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec']
  return `${String(d.getUTCDate()).padStart(2, '0')} ${months[d.getUTCMonth()]} ${d.getUTCFullYear()}`
}

interface TreeRowProps {
  node:      ECTDNode
  active:    boolean
  onClick:   () => void
  flagged:   boolean
}
function TreeRow({ node, active, onClick, flagged }: TreeRowProps) {
  const indent = (node.moduleSection.split('.').length - 1) * 10
  return (
    <button
      type="button"
      onClick={onClick}
      data-tree-row={node.id}
      data-tree-active={active || undefined}
      data-tree-read-only={node.isReadOnly || undefined}
      data-tree-flagged={flagged || undefined}
      className="flex w-full items-center gap-2 rounded-md px-2 py-1.5 text-left"
      style={{
        backgroundColor: active ? '#FFF5F5' : 'transparent',
        borderLeft:      active ? '3px solid #B0200D' : '3px solid transparent',
      }}
    >
      <span style={{ width: indent }} />
      <span className="font-mono text-[10px] flex-none w-14 text-slate-500">{node.moduleSection}</span>
      <span className="min-w-0 flex-1 truncate text-[12px] text-slate-800">{node.sectionTitle}</span>
      {flagged && (
        <span
          className="inline-flex items-center rounded px-1 text-[10px] font-semibold"
          style={{ backgroundColor: '#FFFBEB', color: '#B45309', border: '1px solid #FDE68A' }}
          data-consistency-flag
          title="Consistency contradiction"
        >⚠</span>
      )}
      <ECTDStatusDot status={node.status} />
      {node.isReadOnly && <span title="Read-only · Module A">🔒</span>}
    </button>
  )
}

export function ECTDGranularityMap() {
  const { projectId, submissionId } = useParams()
  const navigate = useNavigate()

  const nodes           = useECTDStore(s => s.nodes)
  const setNodes        = useECTDStore(s => s.setNodes)
  const activeNodeId    = useECTDStore(s => s.activeNodeId)
  const setActiveNodeId = useECTDStore(s => s.setActiveNodeId)

  const [toast, setToast] = useState<string | null>(null)
  const [isRunningCheck, setRunningCheck] = useState(false)
  const [consistencyResult, setConsistencyResult] = useState<ConsistencyCheckResult | null>(null)
  const [showReadOnlyBanner, setShowReadOnlyBanner] = useState(false)

  const flash = (msg: string) => { setToast(msg); setTimeout(() => setToast(null), 3200) }

  const { data: fetched = [] } = useQuery({
    queryKey: ['reg-ectd-map', submissionId],
    queryFn:  () => regulatoryWritingApi.getECTDMap(submissionId!),
    enabled:  !!submissionId,
  })
  const { data: fetchedCC } = useQuery({
    queryKey: ['consistency', submissionId],
    queryFn:  () => regulatoryWritingApi.getConsistencyCheck(submissionId!),
    enabled:  !!submissionId,
  })

  useEffect(() => { setNodes(fetched as ECTDNode[]) }, [fetched, setNodes])
  useEffect(() => { if (fetchedCC) setConsistencyResult(fetchedCC as ConsistencyCheckResult) }, [fetchedCC])

  // Default selection — nd-018 (2.5.4)
  useEffect(() => {
    if (!activeNodeId && nodes.length > 0) {
      const defaultNode = nodes.find(n => n.id === 'nd-018') ?? nodes[0]
      setActiveNodeId(defaultNode.id)
    }
  }, [nodes, activeNodeId, setActiveNodeId])

  const selected = nodes.find(n => n.id === activeNodeId) ?? null

  const counts = useMemo(() => ({
    total:         nodes.length,
    compiled:      nodes.filter(n => n.status === 'signed').length,
    inAuthoring:   nodes.filter(n => n.status === 'in-authoring').length,
    inReview:      nodes.filter(n => n.status === 'in-review').length,
    notStarted:    nodes.filter(n => n.status === 'not-started').length,
    autoGenerated: nodes.filter(n => n.status === 'auto-generated').length,
    readOnly:      nodes.filter(n => n.status === 'read-only').length,
  }), [nodes])

  const completedPct = counts.total === 0 ? 0 : Math.round((counts.compiled / counts.total) * 100)

  const runCheckMutation = useMutation({
    mutationFn: () => {
      setRunningCheck(true)
      return regulatoryWritingApi.runConsistencyCheck(submissionId!)
    },
    onSuccess: (data) => {
      setConsistencyResult(data.result as ConsistencyCheckResult)
      setRunningCheck(false)
      flash('Cross-module consistency check complete.')
    },
    onError: () => setRunningCheck(false),
  })

  const handleNodeClick = (node: ECTDNode) => {
    if (node.isReadOnly) {
      setShowReadOnlyBanner(true)
      setActiveNodeId(node.id)
      return
    }
    setShowReadOnlyBanner(false)
    setActiveNodeId(node.id)
  }

  const openInEditor = () => navigate(`/projects/${projectId}/regulatory-writing/submissions/${submissionId}/module2-editor`)

  const sectionContradictions = useMemo(() => {
    if (!consistencyResult || !selected) return []
    return consistencyResult.contradictions.filter(c =>
      c.sourceSection.includes(selected.moduleSection) || c.targetSection.includes(selected.moduleSection),
    )
  }, [consistencyResult, selected])

  return (
    <div className="bg-slate-50" data-screen="ectd-granularity-map">
      <div className="mx-auto flex flex-col gap-4" style={{ maxWidth: 1440, padding: '16px 24px 24px' }}>

        {/* Breadcrumb */}
        <nav className="flex items-center gap-2 text-xs text-slate-500">
          <button onClick={() => navigate(`/projects/${projectId}/regulatory-writing`)} className="hover:text-slate-900">Regulatory Writing</button>
          <span style={{ color: '#CBD5E1' }}>&gt;</span>
          <button onClick={() => navigate(`/projects/${projectId}/regulatory-writing/submissions/${submissionId}`)} className="hover:text-slate-900">Veloricept NDA</button>
          <span style={{ color: '#CBD5E1' }}>&gt;</span>
          <span className="font-semibold text-slate-900">eCTD Granularity Map</span>
        </nav>

        {/* Header */}
        <div className="flex flex-wrap items-start justify-between gap-6">
          <div className="flex min-w-0 flex-col gap-1.5">
            <h1 className="text-[22px] font-bold text-slate-900" style={{ margin: 0 }}>eCTD Granularity Map · Veloricept NDA · FDA + EMA</h1>
            <div className="flex items-center gap-3 text-[12px]" data-completeness>
              <span className="text-slate-600">{counts.compiled} of {counts.total} sections ✓ · <strong>{completedPct}%</strong></span>
              <div className="h-2 w-40 overflow-hidden rounded-full bg-slate-100">
                <div className="h-full" style={{ width: `${completedPct}%`, backgroundColor: '#B0200D' }} data-completeness-bar />
              </div>
            </div>
          </div>
          <div className="flex flex-none gap-2">
            <button
              type="button"
              onClick={() => flash('eCTD map PDF export queued.')}
              data-export-map
              className="h-9 rounded-md border border-slate-300 bg-white px-3 text-[13px] font-semibold text-slate-700"
            >Export map (PDF)</button>
            <button
              type="button"
              onClick={() => runCheckMutation.mutate()}
              disabled={isRunningCheck}
              data-run-consistency
              className="h-9 rounded-md px-3 text-[13px] font-semibold text-white"
              style={{ backgroundColor: isRunningCheck ? '#CBD5E1' : '#D97706' }}
            >{isRunningCheck ? 'Running…' : 'Run consistency check ✦'}</button>
          </div>
        </div>

        <div className="grid gap-4" style={{ gridTemplateColumns: '340px minmax(0,1fr)' }}>
          {/* LEFT — Tree */}
          <aside className="rounded-lg border border-slate-200 bg-white p-3" data-ectd-tree>
            <p className="mb-2 font-mono text-[10px] uppercase text-slate-500" style={{ letterSpacing: '0.1em' }}>CTD Tree</p>
            <div className="flex flex-col gap-0.5">
              {nodes.map(n => (
                <TreeRow
                  key={n.id}
                  node={n}
                  active={activeNodeId === n.id}
                  flagged={FLAGGED_NODE_IDS.has(n.id)}
                  onClick={() => handleNodeClick(n)}
                />
              ))}
            </div>
          </aside>

          {/* RIGHT — Section detail */}
          <section className="flex flex-col gap-4" data-section-detail>
            {showReadOnlyBanner && selected?.isReadOnly && <CTDReadOnlyBanner />}

            {selected && !selected.isReadOnly && (
              <div className="rounded-lg border border-slate-200 bg-white p-5">
                <div className="flex flex-wrap items-start justify-between gap-3">
                  <div className="min-w-0 flex-1">
                    <p className="font-mono text-[11px] uppercase text-slate-500" style={{ letterSpacing: '0.08em' }}>{selected.moduleSection}</p>
                    <h2 className="text-[18px] font-bold text-slate-900">{selected.sectionTitle}</h2>
                    <p className="mt-1 text-[12px] text-slate-500" data-section-status>
                      <ECTDStatusDot status={selected.status} label /> · v0.4 · Last edited {formatDate(selected.lastUpdated)} by Dr Sarah Chen
                    </p>
                  </div>
                  <div className="flex flex-none flex-col items-end gap-2">
                    <span
                      className="inline-flex items-center gap-1.5 rounded-md px-2 py-0.5 text-[11px] font-semibold"
                      style={{ backgroundColor: '#FFF5F5', color: '#B0200D', border: '1px solid #FFC5C5' }}
                      data-ai-footprint
                    >AI footprint · 51% ✦</span>
                    <button
                      type="button"
                      onClick={openInEditor}
                      data-open-in-editor
                      className="h-8 rounded-md px-3 text-[12px] font-semibold text-white"
                      style={{ backgroundColor: '#B0200D' }}
                    >Open in editor →</button>
                  </div>
                </div>

                {/* Source grounding */}
                <div className="mt-4 rounded-md bg-slate-50 p-3" data-source-grounding>
                  <p className="text-[11px] font-mono uppercase text-slate-500" style={{ letterSpacing: '0.06em' }}>Source grounding</p>
                  <span className="mt-1 inline-flex items-center gap-1.5 rounded-md px-2 py-0.5 text-[11px] font-semibold"
                        style={{ backgroundColor: '#EFF6FF', color: '#005F8E', border: '1px solid #93C5FD' }}>
                    <span className="inline-block h-1.5 w-1.5 rounded-full" style={{ backgroundColor: '#005F8E' }} />
                    Drafted from: VELORA-301 CSR v1.0 · Module A
                  </span>
                  <p className="mt-2 font-mono text-[11px] text-slate-500">214 data points from canonical JSON layer · Indexed 12 Oct 2026.</p>
                </div>

                {/* Cross-references */}
                <div className="mt-4" data-cross-references>
                  <p className="text-[11px] font-mono uppercase text-slate-500" style={{ letterSpacing: '0.06em' }}>Cross-references</p>
                  <p className="mt-1 text-[13px] text-slate-800">
                    Cross-references to Module 5: <strong>18 verified ✓</strong> · <strong style={{ color: '#B45309' }}>2 flagged ⚠</strong>
                  </p>
                  <div className="mt-3 flex flex-col gap-2">
                    {sectionContradictions.map(c => (
                      <ConsistencyContradictionCard key={c.id} contradiction={c} />
                    ))}
                    {sectionContradictions.length === 0 && (
                      <p className="text-[12px] text-slate-500">No contradictions flagged for this section.</p>
                    )}
                  </div>
                  <button
                    type="button"
                    onClick={() => runCheckMutation.mutate()}
                    className="mt-2 text-[12px] font-semibold"
                    style={{ color: '#B0200D' }}
                    data-run-cross-module
                  >Run cross-module check ✦</button>
                </div>

                {/* Publishing status */}
                <div className="mt-4 rounded-md bg-slate-50 p-3" data-publishing-status>
                  <p className="text-[13px] text-slate-800">
                    Continuous publishing: section will compile automatically when locked. <em>Not yet locked.</em>
                  </p>
                  <p className="mt-1 text-[12px] text-slate-500">Sections drafted: 4 of 7 · 57%</p>
                </div>
              </div>
            )}

            {selected && selected.isReadOnly && (
              <div className="rounded-lg border border-slate-200 bg-white p-5">
                <p className="font-mono text-[11px] uppercase text-slate-500" style={{ letterSpacing: '0.08em' }}>{selected.moduleSection}</p>
                <h2 className="text-[18px] font-bold text-slate-900">{selected.sectionTitle}</h2>
                <p className="mt-3 text-[13px] text-slate-600">
                  Module 5 sections are managed in Module A. To modify this CSR, open the source project in Module A and create a new CSR version.
                </p>
              </div>
            )}
          </section>
        </div>

        {/* Bottom strip */}
        <div
          className="grid gap-3 rounded-lg border border-slate-200 bg-white p-3 font-mono text-[11px] text-slate-600 md:grid-cols-6"
          data-bottom-strip
        >
          <span>Total <strong style={{ color: '#0F172A' }}>{counts.total}</strong></span>
          <span>Compiled <strong style={{ color: '#15803D' }}>{counts.compiled}</strong></span>
          <span>In authoring <strong style={{ color: '#1D4ED8' }}>{counts.inAuthoring}</strong></span>
          <span>In review <strong style={{ color: '#B45309' }}>{counts.inReview}</strong></span>
          <span>Not started <strong style={{ color: '#64748B' }}>{counts.notStarted}</strong></span>
          <span>Auto-generated <strong style={{ color: '#B0200D' }}>{counts.autoGenerated}</strong></span>
        </div>
        <div
          className="grid gap-2 font-mono text-[11px] text-slate-500 md:grid-cols-3"
          data-bottom-meta
        >
          <span>Last consistency check: {consistencyResult ? formatDate(consistencyResult.runAt) : '—'} · {consistencyResult?.contradictions.length ?? 0} contradictions found</span>
          <span>eCTD version: v3.2.2 · Validator: EXTEDO EXTEDOpulse</span>
          <span>Gateway: FDA ESG (Priority 1) · EMA CESP (Priority 2)</span>
        </div>
      </div>

      {toast && (
        <div
          data-toast
          className="pointer-events-none fixed bottom-5 left-1/2 flex -translate-x-1/2 items-center gap-2.5 rounded-lg px-4 py-3 text-[13px]"
          style={{ backgroundColor: '#1E293B', color: '#FFFFFF' }}
        >
          <span className="inline-block h-1.5 w-1.5 rounded-full" style={{ backgroundColor: '#B0200D' }} />
          {toast}
        </div>
      )}
    </div>
  )
}
